// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prgolgjtuciyhkvuamjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZ29sZ2p0dWNpeWhrdnVhbWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDc3NTUsImV4cCI6MjA3MjMyMzc1NX0.o4t8tF4j3MVvAVOKJTWHrjFuugWnTFV2b0Cj0EuoSIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});